// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_UsuarioCreadorNavigation = new HashSet<tbUsuarios>();
            Inverseusua_UsuarioModificadorNavigation = new HashSet<tbUsuarios>();
            tbBoletosbole_UsuarioCreadorNavigation = new HashSet<tbBoletos>();
            tbBoletosbole_UsuarioModificadorNavigation = new HashSet<tbBoletos>();
            tbClientesclie_UsuarioCreadorNavigation = new HashSet<tbClientes>();
            tbClientesclie_UsuarioModificadorNavigation = new HashSet<tbClientes>();
            tbDepartamentosdept_UsuarioCreadorNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdept_UsuarioModificadorNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosempl_UsuarioCreadorNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempl_UsuarioModificadorNavigation = new HashSet<tbEmpleados>();
            tbHorarioshora_UsuarioCreadorNavigation = new HashSet<tbHorarios>();
            tbHorarioshora_UsuarioModificadorNavigation = new HashSet<tbHorarios>();
            tbMunicipiosmuni_UsuarioCreadorNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuarioModificadorNavigation = new HashSet<tbMunicipios>();
        }

        public int usua_ID { get; set; }
        public string usua_Usuario { get; set; }
        public byte[] usua_Clave { get; set; }
        public string usua_Pass { get; set; }
        public bool? usua_EsAdmin { get; set; }
        public int? empl_ID { get; set; }
        public int? usua_Estado { get; set; }
        public int? usua_UsuarioCreador { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificador { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios usua_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbBoletos> tbBoletosbole_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbBoletos> tbBoletosbole_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbHorarios> tbHorarioshora_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbHorarios> tbHorarioshora_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioModificadorNavigation { get; set; }
    }
}